version: "3.9"

services:
  db:
    image: postgres:13.9
    env_file:
     - .env
  web:
    build: .
    volumes:
      - .:/code
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  postgres_data: